//Escribir un programa que muestre por consola la tabla de multiplicar del 1 al 10
let num = parseInt(prompt("ingrese el número al multiplicar"));
let n1 = 1 * num;
let n2 = 2 * num;
let n3 = 3 * num;
let n4 = 4 * num;
let n5 = 5 * num;
let n6 = 6 * num;
let n7 = 7 * num;
let n8 = 8 * num;
let n9 = 9 * num;
let n10 = 10 * num;
alert(`1 x ${num} = ${n1}
2 x ${num} = ${n2}
3 x ${num} = ${n3}
4 x ${num} = ${n4}
5 x ${num} = ${n5}
6 x ${num} = ${n6}
7 x ${num} = ${n7}
8 x ${num} = ${n8}
9 x ${num} = ${n9}
10 x ${num} = ${n10}`);